### PR TITLE
PIA VPN check endpoint

### PR DESCRIPTION
**Pull request by lucasrangit**
Hi @Lars- , your project is awesome. I was looking for a way around PIA's lack of verification endpoint like https://mullvad.net/en/check/ when I found your repo. Using your list I was able to create a static website that could be used to check if your connection is protected by PIA. 

Here's an example:

```sh
$ curl https://lucasrangit.github.io/PIA-servers/95.181.239.7
You are protected by PIA
$ curl https://lucasrangit.github.io/PIA-servers/1.2.3.4
You are not connected to PIA
$ curl -s https://lucasrangit.github.io/PIA-servers/$(curl -s https://am.i.mullvad.net/ip)
You are not connected to PIA
```

I wanted to run it by you before I put any more effort in. If you think it's useful, I'll make the following improvements.

* See if there's a way for a static site to lookup your WAN IP (doubt it).
* Generating the files automatically with GitHub Pages (or Actions) instead of storing them in the repository.

### CODE REVIEW

**Comment by Lars-** [comment]
Hi @lucasrangit 

I really like the idea! Nice job.

The only thing that I'm not immediately happy about are the massive amount of doc files. Do you think there would be another way to do it? I'm thinking about simply creating a folder with all the IPs in it (I was thinking about rebuilding this repo anyway) and checking it that way, but that wouldn't give you the nice "you are connected" message... If there is no alternative, I'm willing to integrate the generation of the doc files, because I do like the message.

And about the status page, you could use ipinfo.io which has a free API that you can call with JS to check the WAN IP. But that wouldn't work on the command line of course, I think the nested curl command is the best you'll get.

Summary: great job, keep going! I'm going to rebuild this repo. Maybe today, maybe tomorrow.

**Comment by lucasrangit** [comment]
> The only thing that I'm not immediately happy about are the massive amount of doc files. Do you think there would be another way to do it? I'm thinking about simply creating a folder with all the IPs in it (I was thinking about rebuilding this repo anyway) and checking it that way, but that wouldn't give you the nice "you are connected" message... If there is no alternative, I'm willing to integrate the generation of the doc files, because I do like the message.

Yes, there are alternatives that don't require the doc files, which is why this is a draft PR. I don't expect this illustrative prototype to be merged as-in. 

Can I see the script(s) you run to generate/update this repo? Maybe the most efficient would be add to that. If not, then I'll rework this to generate the files using GitHub Pages or Actions. 

I'm not sure if reorganize the repo makes more sense; it depends on your primary use-case(s). For me it's just checking if my Wireguard connection is protected by PIA. I'm not using the OpenVPN configurations anymore.

**Comment by Lars-** [comment]
I understand what you mean and I agree. That's why today I rebuilt the whole system and added instructions to the readme to check if you are connected to PIA.
Thanks for the helpful feedback!

**Comment by lucasrangit** [comment]
Why did the server count go from 15k to 1300?

**Comment by lucasrangit** [comment]
> 

Oh I see. It's up to 7000 now. That's fast.

**Pull request closed without merging**
