### PR TITLE
Use Netlify to create API endpoint

### PR DESCRIPTION
**Pull request by lucasrangit**
Hi @Lars- , I setup the https://pia-servers.netlify.app/check API endpoint for this project to avoid needing to check your WAN IP first. 

```bash
$ curl -s https://pia-servers.netlify.app/check
Hello, 1.2.3.4
You are not protected by PIA
$ curl https://pia-servers.netlify.app/check
Hello, 154.13.1.136
You are protected by PIA
```

I log the IP as a test and will remove it later.

Like before this uses a shell script to parse your IP files that you create under `docs/`. You can get rid of these thousands of IP address files under `docs/ by incorporating the following into your servers update script (I assume you are using `bash`. Where `$servers` is a list/array of IPs you've collected in your database.

```bash
cat << EOF > netlify/functions/check.js
exports.handler = async (event, context) => {
  const servers = "${servers[@]}";
  client_ip = event.headers['x-nf-client-connection-ip'];
  protected_status = servers.includes(client_ip) ? "You are protected by PIA" : "You are not protected by PIA";
  return {
    statusCode: 200,
    body: "Hello, " + client_ip + '\n' + protected_status + '\n',
  };
};
EOF
```

Netlify's pricing includes 300 free minutes for build time and 125k lambda call per month. The build takes 21 seconds (less once you remove the IP files under `docs/`) so if you run 4 times a day it will consume 42 minutes. I'm not sure how popular the API endpoint will be ;)

### CODE REVIEW

**Comment by lucasrangit** [comment]
@Lars- maybe you can share access to the private repo that updates the database and generates this repo and I can make a PR there?

**Comment by Lars-** [comment]
The repo is not on Github, but on my private git server. And it's written in PHP. I think the docs folder works the easiest, doesn't it?

**Comment by lucasrangit** [comment]
> The repo is not on Github, but on my private git server. And it's written in PHP.

👍🏽  PHP is no problem. If ever you want help with it create a free private repo on Github and let me know. I'm more than happy to help.

> I think the docs folder works the easiest, doesn't it?

You said you didn't like the massive amount of doc files 😕 which is why I turned it into an API like https://api.nordvpn.com/vpn/check .

**Comment by Lars-** [comment]
I added you as a collaborator to a Github clone of the private repo. Feel free to edit it as much as you like.

**Comment by kylefmohr** [comment]
@Lars- Hi, apologies for the off-topic comment, but there's no way to open an issue on this repo. I was wondering if it would be possible to update the script to add recently added PIA locations in Wisconsin and Minnesota. If you were to add me to the private repo I could take a look and possibly open a PR for this (although it's been a couple years since I've done anything in PHP, I'd be happy to try). Thanks for this useful resource. 

And just to confirm - I am currently connected to a PIA server in MN and https://pia-servers.netlify.app/check says I'm *not* connected to PIA

**Comment by Lars-** [comment]
@kylefmohr thanks for your message. I enabled issues and I will check if it's possible to add those locations tomorrow.

**Comment by Lars-** [comment]
@kylefmohr I don't know where you fot the netlify link, but there is another link in the Readme. Does that also say that you're not connected to PIA?

**Comment by Lars-** [comment]
@kylefmohr Minnesota and Wisconsin are not in the file that PIA provides: https://www.privateinternetaccess.com/openvpn/openvpn.zip 
So they can't be added.

**Comment by kylefmohr** [comment]
@Lars- No problem, thanks for checking. 

Yeah, running the curl -s command while connected to a Minnesota PIA VPN results in the same: `You are not connected to PIA`

I got the Netlify link from the first post in this pull request (direct link: https://github.com/Lars-/PIA-servers/pull/4#issue-1159556548)

**Comment by kylefmohr** [comment]
> @kylefmohr Minnesota and Wisconsin are not in the file that PIA provides: https://www.privateinternetaccess.com/openvpn/openvpn.zip So they can't be added.

@Lars- I just reached out to PIA's support team and I'll open a new issue (or PR if I am able to fix it myself) if and when they update the .zip file with the new locations. Thanks again.

**Comment by Lars-** [comment]
@kylefmohr Cool. If they update the zip, the locations should automatically be added to the repo.

**Pull request closed without merging**
